### ISSUE TITLE
Omit PCI 0 from most common value calculation on map

### ISSUE THREAD

**Issue by veixes** [CellMapper/CellMapper-Android-App#54]
If not already done, then when calculating the most common value for PCI value on cell info then do not count PCI 0 if there is already other known values available.
PCI 0 is 99,99% not the right PCI value for cell, so including it in most common value calculation(maybe too many faulty devices reported it) does not make the info more accurate.

**Comment by zivan56** [comment]
It used to do this, but I received complaints about PCI = 0 not showing up.
There is logic in place to see if PCI is really 0 or not.  If it detects 10 values of that PCI for the cell not equal to 0, then it will not consider 0.  It seems like these devices are completely faulty and report 0, and are the only ones to map this cell, which is why it is 0.
