### ISSUE TITLE
Feature request : Select showed Bandwidth( 4G/3G/2G) on cell map, independent of actual used bandwidth

### ISSUE THREAD

**Issue by alinderom** [CellMapper/CellMapper-Android-App#72]
Hi,
according to the manual the map on the cell phone shows measured points of the actual bandwidth.  For filling in the gaps of measuring points in CellMapper, it would be usefull for being able to select the bandtwidth measuring points you want to show on the map.

**Comment by olkitu** [comment]
You mean can filter as B3@20Mhz, B20@10Mhz? Or what you mean bandwith?

**Comment by alinderom** [comment]
With bandwidth i mean 2G-3G-4G (as the selections on "cellmapper.net)
Reason : in order to fully fill the CellMapper database. I sometimes take alternative roads to have more measurments for better triangulation. In CellMapper all measured point are placed in 2G, 3G or 4G. So if i want to measure the coverage of 3G, and I am in temporary in a zone with only 2G, I still want to see the 3G measuring points on the map.

**Comment by olkitu** [comment]
That it not possible because...

1st map too messy adding different mobile technology same map
2nd your browser will crash loading too much data

But we have idea some low level what showing only coverage area, not cell information or locations. Similar map as mostly provider have but we calculate that from our database.

**Comment by alinderom** [comment]
OK, I think I found another solution. I force my cell phone to go on an older( slower) band  and the map is corrected to that band.
